package io.github.youndie.viddik.gradle

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import org.gradle.work.DisableCachingByDefault

/**
 * Writes the JUnit 5 class that drives the goldens, for the `viddik { showroomTargets = true }` shape
 * where the fixtures — and therefore the registry — live in `commonMain`.
 *
 * The processor emits this class itself whenever it finds fixtures in the source set it is running
 * over. It cannot here, and not because it would refuse to: KSP skips a source set with no Kotlin
 * files in it at all (`kspTestKotlinDesktop NO-SOURCE`), and a module whose fixtures moved to
 * `commonMain` typically has exactly that — an empty test source set. The result would be a
 * `viddikVerify` that passes with no tests in it, which is the one failure this plugin exists to make
 * impossible.
 *
 * A Gradle task has no such escape: it has an output directory, so it runs.
 */
@DisableCachingByDefault(
    because = "The output is a fixed string; writing it is cheaper than looking it up in a build cache.",
)
public abstract class ViddikGenerateTestsTask : DefaultTask() {
    @get:OutputDirectory
    public abstract val outputDir: DirectoryProperty

    /**
     * Whether `viddik { showroomTargets }` is on. An input rather than an `onlyIf`, so that turning
     * the flag off re-runs the task and takes the file away again — an `onlyIf` would skip the task
     * and leave a test class behind that references a registry no longer being generated.
     *
     * Not called `enabled`: `Task` already has a Boolean property by that name, and Gradle refuses to
     * decorate a type that shadows it with an abstract one.
     */
    @get:Input
    public abstract val showroomTargets: Property<Boolean>

    @TaskAction
    public fun generate() {
        val root = outputDir.get().asFile
        root.deleteRecursively()
        if (!showroomTargets.get()) return
        val target = root.resolve(PACKAGE.replace('.', '/'))
        target.mkdirs()
        target.resolve("GeneratedViddikTests.kt").writeText(SOURCE)
    }

    private companion object {
        const val PACKAGE = "io.github.youndie.viddik.generated"

        // Character for character what the processor writes for a module whose fixtures are in the
        // test source set, so a module that moves them to commonMain gets the same test class, under
        // the same name, matched by the same `*GeneratedViddikTests*` filter.
        val SOURCE =
            """
            // Generated by the io.github.youndie.viddik Gradle plugin. Do not edit.
            package $PACKAGE

            import io.github.youndie.viddik.core.ViddikEngine
            import org.junit.jupiter.api.DynamicTest
            import org.junit.jupiter.api.TestFactory

            public class GeneratedViddikTests {
                @TestFactory
                public fun runAllScreenshots(): List<DynamicTest> =
                    ViddikEngine.dynamicTests(GeneratedViddikRegistry.components)
            }

            """.trimIndent()
    }
}
