plugins {
    kotlin("jvm")
    `java-gradle-plugin`
    alias(libs.plugins.dokka)
    alias(libs.plugins.sborkaJvm)
    alias(libs.plugins.sborkaLint)
    alias(libs.plugins.sborkaPublish)
}

// The version used to be patched onto the project here by hand, because the old convention set it on
// the publications instead and a plugin marker captures `project.version` when `java-gradle-plugin`
// creates it — a marker pointing at a version that was never published. `sborka.base` sets the
// project version for every module, so the special case is gone rather than moved.

kotlin {
    explicitApi()
}

dependencies {
    // Both are `compileOnly`: the plugin is compiled against these APIs but must run against
    // whatever KGP/KSP version the consumer's build already has — KSP in particular is pinned to
    // the consumer's exact Kotlin compiler version, so shipping our own would be actively wrong.
    compileOnly(libs.kotlin.gradle.plugin)
    compileOnly(libs.ksp.gradle.plugin)

    testImplementation(kotlin("test"))
}

gradlePlugin {
    plugins {
        create("viddik") {
            id = "io.github.youndie.viddik"
            implementationClass = "io.github.youndie.viddik.gradle.ViddikPlugin"
            displayName = "viddik screenshot testing"
            description =
                "Wires viddik screenshot testing into a Compose Multiplatform or plain JVM module: " +
                "dependencies, KSP processor, generated-source directory and the record/verify tasks."
        }
    }
}

// The versions the plugin hands to consumers travel as a resource rather than generated Kotlin: no
// generated source directory means nothing for ktlint or Dokka to trip over, and the values stay
// readable at configuration time without a task dependency.
val versionResource =
    tasks.register<WriteProperties>("generateViddikVersionResource") {
        destinationFile = layout.buildDirectory.file("generated/viddik-resources/viddik-plugin.properties")
        comment = "Generated by :viddik-gradle-plugin — do not edit."
        property("viddik.version", providers.provider { project.version.toString() })
        property("junit.jupiter.version", libs.versions.junitJupiter.get())
        property("junit.platform.version", libs.versions.junitPlatform.get())
    }

sourceSets.main {
    resources.srcDir(
        versionResource.map {
            it.destinationFile
                .get()
                .asFile.parentFile
        },
    )
}

tasks.withType<Test>().configureEach {
    useJUnitPlatform()
}
